spring:
  application:
    name: ny-archive-be

  datasource:
    # MySQL 드라이버 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql 경로 입력
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    # hibernate:
    # 서버 실행 시 엔티티를 보고 테이블을 자동으로 업데이트 해줌
    # ddl-auto: update
    # 실행되는 SQL 쿼리를 콘솔창에 예쁘게 보여주는 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 스웨거 설정
springdoc:
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  swagger-ui:
    # 접속 경로를 설정해
    path: /swagger-ui.html
    # API 정렬 순서
    operations-sorter: alpha