spring:
  application:
    name: ny-archive-be

  datasource:
    # MySQL 드라이버 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql 경로 입력
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    # 실행되는 SQL 쿼리를 콘솔창에 예쁘게 보여주는 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    # 파일 크기
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB

# 스웨거 설정
springdoc:
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  swagger-ui:
    # 접속 경로를 설정해
    path: /swagger-ui.html
    # API 정렬 순서
    operations-sorter: alpha